port: 3000
title: API Page
descr: "A simple api page"
track: http://localhost:3001
copyright:
  author: Halyul
  since: 2018
locales:
  - zh-CN # this is the default language
  - en
zh-CN:
  title: API页面
  descr: "假装自己是一个提供api的dalao"
en:
  title: API Page
  descr: "Pretending I have api to provide"
